lang: en
title: Frontle
tagline: The easiest multi-platform SPA framework
email: y37653@artifriends.com
description: >
  The easiest multi-platform SPA framework
baseurl: ""
url: "https://frontle.org"
permalink: pretty
hide_share_buttons: true
disqus:
  shortname: frontle

plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-feed
  - jekyll-seo-tag
  - kramdown-parser-gfm
  - jekyll-redirect-from

exclude:
  - Gemfile
  - clean-theme.gemspec
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

livereload: true

sass:
  style: compressed
  source_dir: _sass

#google_analytics: UA-code-here

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      show_sidebar: false

markdown: kramdown
highlighter: rouge
footer_menu: footer_menu
